### ISSUE TITLE
JustDo | Toggle completed tasks as completed in Firestore

### ISSUE THREAD

**Issue by Quentara** [Quentara/portfolio#1]
Tasks the user clicks on in the browser get added the completed css class. Therefore they are visually completed but will be reloaded as incomplete after the next refresh. A click on the todo has to toggle a boolean to false in the Firestore database.

**User Story:**
> As a user i can click on a todo and it will be marked as completed. Therefore it will no longer be shown in my todo list.

**Tasks to complete story:**
- [x] Visually mark task as completed (CSS class)
- [x] Search for clicked todo object in Firestore document
- [x] Toggle boolean 'completed' to true
- [x] Push updated todo object to Firestore document
- [x] Reload todo list without completed todos

**Comment by Quentara** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Toggle todos as completed](https://trello.com/c/7zdAWQtp/7-toggle-todos-as-completed)

**Comment by Quentara** [comment]
Feature implemented.
